- title: Getting Started
  items:
    - title: Installation
      to: /getting-started/installation
    - title: Usage
      to: /getting-started/usage
    - title: First Project
      to: /getting-started/first-project
    - title: Project Structure
      to: /getting-started/project-structure
