- title: API
  items:
    - title: Configuration
      to: /api/configuration
    - title: Managers
      to: /api/managers
    - title: Types
      to: /api/types
    - title: Commands
      to: /api/commands
