- title: Examples
  items:
    - title: TaskMaster
      to: /examples/taskmaster
    # - title: NFT Marketplace
    #   to: /examples/nft-marketplace
    # - title: DeFi Protocol
    #   to: /examples/defi-protocol
    # - title: Token Contract
    #   to: /examples/token-contract
